[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy-inspector-egui.workspace = true
bincode.workspace = true
net.workspace = true
serde.workspace = true
